### ISSUE TITLE
contao-facebook_widgets AND contao-facebook-albums at the same time on one page

### ISSUE THREAD

**Issue by peter-weiss** [codefog/contao-facebook_widgets#2]
It looks like **contao-facebook_widgets** and **contao-facebook-albums** are sharing the same Facebook class.

I get the following error message:
PHP Fatal error:  Call to undefined method Facebook\Facebook::generateLikeBox() in /.../system/modules/facebook_widgets/hybrids/FacebookLikeBox.php on line 50

When I turn off "contao-facebook_widgets", the extension "contao-facebook-albums" works like a charm and vice versa.

**Comment by qzminski** [comment]
It should be fixed in the develop branch, can you try it out?

**Comment by peter-weiss** [comment]
Works perfect now, thank you!
